name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test-input-validation:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - name: input-subcommand-missing-test
        id: input-subcommand-missing-test
        continue-on-error: true
        uses: ./
      - name: input-subcommand-missing-assert-failure
        run: |
          [ "${{ steps.input-subcommand-missing-test.outcome }}" = "failure" ]
      - name: input-subcommand-wrong-test
        id: input-subcommand-wrong-test
        continue-on-error: true
        uses: ./
        with:
          subcommand: bad
      - name: input-subcommand-wrong-assert-failure
        run: |
          [ "${{ steps.input-subcommand-wrong-test.outcome }}" = "failure" ]
